### ISSUE TITLE
Renaming repo

### ISSUE THREAD

**Issue by JanJereczek** [palma-ice/FastIsostasy#9]
`isostasy` might be a too generic name (especially when we refer to it orally). I think we can come up with something more specific like:
- `regional-gia`
- `regional-isostasies`
- `fastisostasy`

I think the last option is not a big conflict to the Julia repo, since the latter will soon include other regional models for the deformational response, needed to compare with LV-ELVA. `fastisostasy` is my preferred option, since the name appears in GMD submission and the Fortran code got much closer to the Julia one :)

**Comment by alex-robinson** [comment]
This has been resolved with the name FastIsostasy!
